package ec.mark.im.common.model;

import io.jboot.db.annotation.Table;
import ec.mark.im.common.base.BaseGroupUsers;

/**
 * Generated by Jboot.
 */
@Table(tableName = "group_users", primaryKey = "id")
public class GroupUsers extends BaseGroupUsers<GroupUsers> {
	private static final long serialVersionUID = -7661332964630933509L;
	
}
