package ec.mark.im.common.model;

import io.jboot.db.annotation.Table;
import ec.mark.im.common.base.BaseGroups;

/**
 * Generated by Jboot.
 */
@Table(tableName = "groups", primaryKey = "id")
public class Groups extends BaseGroups<Groups> {
	private static final long serialVersionUID = -6157707530048856875L;
	
}
