package ec.mark.im.common.model;

import io.jboot.db.annotation.Table;
import ec.mark.im.common.base.BaseUserGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_group", primaryKey = "id")
public class UserGroup extends BaseUserGroup<UserGroup> {
	private static final long serialVersionUID = -1582352238078007515L;
	
}
