package ec.mark.im.common.model;

import io.jboot.db.annotation.Table;
import ec.mark.im.common.base.BaseUsers;

/**
 * Generated by Jboot.
 */
@Table(tableName = "users", primaryKey = "id")
public class Users extends BaseUsers<Users> {
	private static final long serialVersionUID = -5784207508354264011L;
	
}
