package ec.mark.im.common.model;

import io.jboot.db.annotation.Table;
import ec.mark.im.common.base.BaseUserFriends;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_friends", primaryKey = "id")
public class UserFriends extends BaseUserFriends<UserFriends> {
	private static final long serialVersionUID = 5746347905415872943L;
	
}
