package ec.mark.im.common.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupUsers<M extends BaseGroupUsers<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	public java.util.Date getJoinTime() {
		return get("join_time");
	}

}
